  version: '4'
  services:
    mongodb:
      image: mongo:latest
      container_name: momgodb
      ports:
        - '27017:27017'
      environment:
        MONGO_INITDB_ROOT_USERNAME : root
        MONGO_INITDB_ROOT_PASSWORD : password
        MONGO_INIT_DATABASE : product-service
      volumes:
        - /home/sasan/Documents/For_Project_II/Learn_micro_service_spring_boot/product-service/data/data/db
